<?php
    
    $MY_PUBLIC_KEY = 'YOUR_PUBLIC_KEY_GOES_HERE';
    $MY_PRIVATE_KEY = 'YOUR_PRIVATE_KEY_GOES_HERE';
    
    $MY_CONFIG_ID = 'ID_OF_CONFIGURATION';
    $MY_GENERATED_LAYOUT_ID = 'ANY_OF_YOUR_LAYOUT_IDS';
    
?>